services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - mynetwork

  ngrok:
    image: wernight/ngrok
    command: ngrok http backend:8080
    ports:
      - "4040:4040"
    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
